### ISSUE TITLE
Atao teny anglais daholo aloha ny menus, dia aminy i18n no atao ny traduction

### ISSUE THREAD

**Issue by rakotomandimby** [julkwel/mylinux#1]
Aleo aloha tsy asiana an'ilay hoe "hamafa", sns... fa atao teny angilisy.
Avy eo atao anaty https://github.com/julkwel/mylinux/tree/master/src/assets/i18n ny traduction
Dia atao Malagasy ny teny par défaut.

PS: Eny, vary amin'anana ilay issue, fa tsy maninona :-)

**Comment by julkwel** [comment]
@rakotomandimby  Ok ho jerena avy hatrany izay
